### ISSUE TITLE
Unable to generate bindata with go 1.11

### ISSUE THREAD

**Issue by jrasillo-boa** [go-bindata/go-bindata#19]
Simple test:
- Create a `bintest` dir directory with binary files
- Run `go-bindata -pkg bintestout -o ./bintestout/files.go ./bintest/*`
- File generated has syntax errors
`syntax error: unexpected {, expecting expression`

**My go version**: 
```sh
go version go1.11.4 linux/amd64
```

**go-bindata version**: 
```sh
go-bindata --version
go-bindata 3.1.0 (Go runtime go1.11.4).
Copyright (c) 2010-2013, Jim Teeuwen.
```
 
[Commit reference](https://github.com/go-bindata/go-bindata/commit/892c73e813678653fa1d22b167fd4cd242f322ff#comments)

**Comment by Ropes** [comment]
Confirming this problem with
```
go version go1.11.1 linux/amd64
```
and
```
$ go-bindata -version
go-bindata 3.1.0 (Go runtime go1.11.1).
Copyright (c) 2010-2013, Jim Teeuwen.
```
Seeing the same `syntax error: unexpected {, expecting expression`

**Comment by veily** [comment]
Fixed this bug . Reinstall go-bindata @3.1.1
