### ISSUE TITLE
go mod support

### ISSUE THREAD

**Issue by H3JFC** [go-bindata/go-bindata#30]
It would be nice if this library played nice with go mod. Currently, when you run go get "github.com/go-bindata/go-bindata" you get the following in your go.mod file "github.com/go-bindata/go-bindata v3.1.2+incompatible" and the library is unavailable to use.

**Comment by dvelitchkov** [comment]
As simple as modifying `go.mod` and appending `/v3` at the end of the module name, according to https://github.com/golang/go/wiki/Modules#faqs--semantic-import-versioning

**Comment by dvelitchkov** [comment]
I'm going to go ahead and say a heresy here - rsc screwed up a bit with the design of vgo. From what I've seen, most people get it "wrong", including this repo. 

https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

Basically the module name in the `go.mod` file has to have `/v3` appended. In addition, should probably have different branches for different major versions if multiple versions are to be maintained.

**Comment by adnanfajlur** [comment]
any update?
