### ISSUE TITLE
golint should ignore bindata.go files

### ISSUE THREAD

**Issue by bminer** [go-bindata/go-bindata#36]
Need to follow the guidelines outlined here: https://golang.org/s/generatedcode

That means that the comment must begin with `// Code generated ` and must end with ` DO NOT EDIT.`

I am referencing this recent commit:

https://github.com/go-bindata/go-bindata/commit/0cb471447831dd56f8a91c58dd5fa3feeacbc8f0#diff-76b9265a0c3cccec7fb95e6bde2f273aR53

I'll also reference how golint recognizes these special comments: https://github.com/golang/lint/commit/a5f4a247366d8fc436941822e14fc3eac7727015

**Comment by narg95** [comment]
Hi all!

is there any progress on this? 

Thanks!

**Comment by narg95** [comment]
This PR should fix it #37

**Comment by bminer** [comment]
Glad to see a PR got merged in.  Closing this issue.
