### ISSUE TITLE
Site does not exist

### ISSUE THREAD

**Issue by kishaningithub** [go-bindata/go-bindata#5]
https://gobindata.github.io site does not exist not does the repo

**Comment by philoserf** [comment]
I have found the easiest way to create a site for my projects is to have a `/docs/` directory with an `index.md` and a `_config.yml`. I put the `README.md` content in `index.md` and make `README.md` a soft link to `index.md`. I then set the GitHub Pages to `/docs`.

See <https://github.com/philoserf/base> for an example.

**Comment by philoserf** [comment]
I removed the broken Github pages setup for the moment.

**Comment by philoserf** [comment]
This issue is in fact complete. If the community desires the site it can be proposed in a new issue.
